server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ps
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

